car-data:
  engine-types: бензиновий, дизельний, гібридний;
  fuel-types:
    бензин:
      - A-95
      - A-98
      - A-100
    дизель:
      - зимовий
      - літній
      - арктичний
    електрика: [ ]

